import type { HomepageContent } from '@shared/schema';

export const DEFAULT_HOMEPAGE_CONTENT: HomepageContent = {
  heroBadgeImageUrl: '',
  heroBadgeAlt: '',
  trustBadges: [],
  categoriesSection: {
    title: 'Our Services',
    subtitle: 'Select a category to learn about our solutions.',
    ctaText: 'Schedule Now',
  },
  reviewsSection: {
    title: 'Customer Reviews',
    subtitle: 'See what our customers say about our services.',
    embedUrl: '',
  },
  blogSection: {
    title: 'Blog',
    subtitle: 'Latest news and articles',
    viewAllText: 'View All',
    readMoreText: 'Read More',
  },
  aboutSection: {
    label: 'About Us',
    heading: 'Who We Are',
    description: 'We are experts in [Your Niche]. We help our clients achieve their goals through high-quality services and personalized attention.',
    defaultImageUrl: '',
    highlights: [
      {
        title: 'Excellence',
        description: 'Commitment to quality in every delivery.',
      },
      {
        title: 'Experience',
        description: 'Years of experience in the market.',
      },
      {
        title: 'Personalized Service',
        description: 'Solutions tailored just for you.',
      },
    ],
  },
  areasServedSection: {
    label: 'Where We Serve',
    heading: 'Service Area',
    description: 'We serve in [Your Region/City]. Contact us to check availability in your area.',
    ctaText: 'Check Availability',
  },
  consultingStepsSection: {
    enabled: true,
    sectionId: 'how-it-works',
    title: 'How It Works',
    subtitle: 'Our simplified process to better serve you.',
    steps: [
      {
        order: 1,
        numberLabel: '01',
        icon: 'search',
        title: 'Diagnosis',
        whatWeDo: 'We understand your needs and goals.',
        outcome: 'Clarity on what needs to be done.',
      },
      {
        order: 2,
        numberLabel: '02',
        icon: 'sparkles',
        title: 'Proposal',
        whatWeDo: 'We present the best solution for your case.',
        outcome: 'A clear plan and transparent budget.',
      },
      {
        order: 3,
        numberLabel: '03',
        icon: 'layout',
        title: 'Execution',
        whatWeDo: 'We put the plan into practice with excellence.',
        outcome: 'Service delivered as agreed.',
      },
      {
        order: 4,
        numberLabel: '04',
        icon: 'target',
        title: 'Delivery',
        whatWeDo: 'We review and deliver the final result.',
        outcome: 'Your satisfaction guaranteed.',
      },
    ],
    practicalBlockTitle: 'In Practice',
    practicalBullets: [
      'Fast and efficient service.',
      'Qualified professionals.',
      'Continuous support.',
    ],
    ctaButtonLabel: 'Contact Us',
    ctaButtonLink: '#lead-form',
    helperText: 'We are ready to help you.',
    tagLabel: 'Consulting',
    stepLabel: 'Step',
    whatWeDoLabel: 'What we do',
    outcomeLabel: 'You get',
    practicalBlockSubtitle: 'How the work happens day-to-day',
    nextStepLabel: 'Next step',
    nextStepText: 'Schedule open for new projects',
  },
};
