import type { HomepageContent } from '@shared/schema';

export const DEFAULT_HOMEPAGE_CONTENT: HomepageContent = {
  heroBadgeImageUrl: 'https://storage.googleapis.com/msgsndr/q6UKnlWOQwyTk82yZPAs/media/696016120597df5bbeeba997.png',
  heroBadgeAlt: 'Trusted Experts',
  trustBadges: [
    { title: '100% Satisfaction Guarantee', description: 'Our quality is guaranteed.', icon: 'star' },
    { title: 'Fully-vetted Cleaning Crew', description: 'Trusted professionals only.', icon: 'shield' },
    { title: 'Upfront Pricing & Easy Booking', description: 'Book in under 60 seconds.', icon: 'clock' },
  ],
  categoriesSection: {
    title: 'Ready to Schedule?',
    subtitle: 'Select a category below to start your instant online booking.',
    ctaText: 'Book Now',
  },
  reviewsSection: {
    title: 'Avaliações de Clientes',
    subtitle: 'Veja o que nossos clientes dizem sobre nossos serviços 5 estrelas.',
    embedUrl: 'https://reputationhub.site/reputation/widgets/review_widget/q6UKnlWOQwyTk82yZPAs',
  },
  blogSection: {
    title: 'Latest from Our Blog',
    subtitle: 'Tips and insights for a cleaner home',
    viewAllText: 'View All Posts',
    readMoreText: 'Read More',
  },
  areasServedSection: {
    label: 'Service Areas',
    heading: 'Areas We Serve',
    description: 'We provide professional cleaning services across Massachusetts and nearby areas. Check the map to see if we cover your location.',
    ctaText: 'Book Now',
  },
  consultingStepsSection: {
    enabled: true,
    sectionId: 'como-funciona',
    title: 'Como Funciona a Consultoria',
    subtitle: 'Um processo claro, em etapas, para você gerar clientes de forma previsível nos EUA.',
    steps: [
      {
        order: 1,
      numberLabel: '01',
      icon: 'search',
      title: 'Diagnóstico e Direção',
      whatWeDo: 'Entendemos seu serviço, sua região, seus concorrentes e seu objetivo (ticket, volume, agenda).',
      outcome: 'Diagnóstico do que está travando + plano de ação simples (prioridades da semana 1).',
    },
    {
      order: 2,
      numberLabel: '02',
      icon: 'sparkles',
      title: 'Oferta Irresistível (sem baixar preço)',
      whatWeDo: 'Ajustamos sua oferta para o padrão do mercado americano (clareza, confiança, diferenciação).',
      outcome: 'Pacote/serviço bem definido + promessa realista + “por que escolher você” em 1 frase.',
    },
    {
      order: 3,
      numberLabel: '03',
      icon: 'layout',
      title: 'Presença Digital que Converte',
      whatWeDo: 'Montamos/ajustamos o que o cliente vê antes de te chamar (site, Google, provas sociais).',
      outcome: 'Estrutura de página/landing + copy essencial + checklist do que precisa estar “redondo” pra converter.',
    },
    {
      order: 4,
      numberLabel: '04',
      icon: 'target',
      title: 'Aquisição de Leads (do jeito certo)',
      whatWeDo: 'Escolhemos os canais que fazem sentido pro seu momento (Google Ads, Local, etc.).',
      outcome: 'Estratégia de captação + segmentação + orçamento recomendado e por quê (sem achismo).',
    },
    {
      order: 5,
      numberLabel: '05',
      icon: 'phone-call',
      title: 'Conversão e Fechamento (sem ficar “correndo atrás”)',
      whatWeDo: 'Criamos seu fluxo de atendimento pra transformar lead em agendamento.',
      outcome: 'Roteiro de conversa (SMS/ligação) + follow-ups + modelo de proposta/fechamento.',
    },
    {
      order: 6,
      numberLabel: '06',
      icon: 'line-chart',
      title: 'Otimização e Escala',
      whatWeDo: 'Ajustamos números, reduzimos desperdício e criamos rotina de melhoria.',
        outcome: 'Plano de otimização (o que medir e quando) + próximos passos pra escalar com consistência.',
    },
    ],
    practicalBlockTitle: 'Na prática',
    practicalBullets: [
      'Sessão inicial pra mapear seu cenário e definir o plano.',
      'Sessões semanais 1:1 com tarefas objetivas (o que fazer, como fazer, e por quê).',
      'Acompanhamento pra ajustar rota e destravar o que estiver impedindo resultado.',
    ],
    ctaButtonLabel: 'Agendar Conversa Gratuita',
    ctaButtonLink: '#lead-quiz',
    helperText: 'Você sai da conversa com clareza do próximo passo — mesmo que não feche a consultoria.',
  },
};
