import type { Express } from "express";
import crypto from "crypto";
import { storage } from "../storage.js";
import { insertPresentationSchema } from "#shared/schema.js";
import { requireAdmin } from "./_shared.js";

export function registerPresentationsRoutes(app: Express) {
  // Literal-segment route registered FIRST — prevents Express matching "slug" as a :id UUID
  // (RESEARCH.md Pitfall 3 guard)
  app.get("/api/presentations/slug/:slug", async (req, res) => {
    try {
      const presentation = await storage.getPresentationBySlug(req.params.slug);
      if (!presentation) return res.status(404).json({ message: "Presentation not found" });

      // If presentation is gated and no code supplied — return metadata + empty slides
      if (presentation.accessCode) {
        const { accessCode, ...safe } = presentation as any;
        return res.json({ ...safe, slides: [], hasAccessCode: true });
      }

      // No gate — return full presentation (strip accessCode field, add hasAccessCode:false)
      const { accessCode, ...publicPresentation } = presentation as any;
      res.json({ ...publicPresentation, hasAccessCode: false });
    } catch (err) {
      res.status(500).json({ message: (err as Error).message });
    }
  });

  // PRES-17 / PRES-21: Verify access code for a gated presentation
  // IDs are UUID strings — do NOT call Number(req.params.id)
  app.post("/api/presentations/:id/verify-code", async (req, res) => {
    try {
      const presentation = await storage.getPresentation(req.params.id);
      if (!presentation) return res.status(404).json({ message: "Presentation not found" });
      if (!presentation.accessCode) return res.json({ success: true });
      const { code } = req.body as { code: string };
      if (presentation.accessCode !== code) {
        return res.status(401).json({ message: "Incorrect code" });
      }
      res.json({ success: true });
    } catch (err) {
      res.status(500).json({ message: (err as Error).message });
    }
  });

  // PRES-17: Record view — called from client after gate is passed
  // SHA-256 hash IP per ip_hash column intent (STATE.md Phase 15 decision)
  app.post("/api/presentations/:id/view", async (req, res) => {
    try {
      const rawIp = ((req.headers["x-forwarded-for"] as string) || req.ip || "").toString();
      const ipHash = rawIp
        ? crypto.createHash("sha256").update(rawIp).digest("hex")
        : undefined;
      await storage.recordPresentationView(req.params.id, ipHash);
      res.json({ success: true });
    } catch (err) {
      res.status(500).json({ message: (err as Error).message });
    }
  });

  // PRES-05: Admin list — returns PresentationWithStats[] sorted by createdAt desc
  // listPresentations() already performs the LEFT JOIN + JSONB count query
  app.get("/api/presentations", requireAdmin, async (_req, res) => {
    try {
      const list = await storage.listPresentations();
      res.json(list);
    } catch (err) {
      res.status(500).json({ message: (err as Error).message });
    }
  });

  // PRES-06: Create — accepts { title }, slug auto-generated by DB defaultRandom()
  // Do NOT generate slug in the route — DB column uses defaultRandom()
  // insertPresentationSchema has slides default([]) so omitting slides is valid
  app.post("/api/presentations", requireAdmin, async (req, res) => {
    try {
      const parsed = insertPresentationSchema.pick({ title: true }).safeParse(req.body);
      if (!parsed.success) {
        return res.status(400).json({ message: "Validation error", errors: parsed.error.errors });
      }
      const presentation = await storage.createPresentation({ title: parsed.data.title, slides: [] });
      res.status(201).json({ id: presentation.id, slug: presentation.slug, slides: presentation.slides });
    } catch (err) {
      res.status(400).json({ message: (err as Error).message });
    }
  });

  // PRES-07: Update — accepts title/slides/accessCode; version NOT in insertPresentationSchema
  // so it must be injected manually as existing.version + 1 (RESEARCH.md Pitfall 2 guard)
  // IDs are UUID strings — do NOT call Number(req.params.id)
  app.put("/api/presentations/:id", requireAdmin, async (req, res) => {
    try {
      const updateSchema = insertPresentationSchema.partial();
      const parsed = updateSchema.safeParse(req.body);
      if (!parsed.success) {
        return res.status(400).json({ message: "Validation error", errors: parsed.error.errors });
      }
      const existing = await storage.getPresentation(req.params.id);
      if (!existing) return res.status(404).json({ message: "Presentation not found" });
      const updated = await storage.updatePresentation(req.params.id, {
        ...parsed.data,
        version: existing.version + 1,
      });
      res.json(updated);
    } catch (err) {
      res.status(400).json({ message: (err as Error).message });
    }
  });

  // PRES-08: Delete — 404-guard before delete; cascade of presentation_views is DB-handled
  app.delete("/api/presentations/:id", requireAdmin, async (req, res) => {
    try {
      const existing = await storage.getPresentation(req.params.id);
      if (!existing) return res.status(404).json({ message: "Presentation not found" });
      await storage.deletePresentation(req.params.id);
      res.json({ success: true });
    } catch (err) {
      res.status(400).json({ message: (err as Error).message });
    }
  });
}
