import type {
  HomepageContent,
  InsertCompanySettings,
  InsertFaq,
  InsertPortfolioService,
} from "../schema.js";

export type PortfolioServiceSeed = InsertPortfolioService & {
  layout?: "left" | "right";
};

export const DEFAULT_TECH_HOMEPAGE_CONTENT: HomepageContent = {
  heroBadgeImageUrl: "",
  heroBadgeAlt: "",
  trustBadges: [
    {
      icon: "zap",
      title: "Fast Implementation",
      description: "Solutions deployed in weeks, not months",
    },
    {
      icon: "shield",
      title: "Enterprise Security",
      description: "Bank-level security standards",
    },
    {
      icon: "trophy",
      title: "Proven Results",
      description: "50+ successful implementations",
    },
  ],
  horizontalScrollSection: {
    enabled: true,
    mode: "services",
    sectionId: "our-solutions",
    tagLabel: "What We Do",
    title: "Tech Solutions That Scale Your Business",
    subtitle: "From AI automation to custom systems - we build what you need to grow",
    cards: [
      {
        order: 1,
        numberLabel: "01",
        icon: "bot",
        title: "AI Solutions",
        description: "Intelligent chatbots, AI agents, and automation that work 24/7 for your business.",
        features: [
          "AI Chatbots & Virtual Assistants",
          "Intelligent Process Automation",
          "Custom AI-Powered Tools",
        ],
      },
      {
        order: 2,
        numberLabel: "02",
        icon: "globe",
        title: "Smart Websites",
        description: "High-converting, SEO-optimized websites that turn visitors into customers.",
        features: [
          "Landing Pages That Convert",
          "Corporate & Portfolio Sites",
          "SEO & Performance Optimization",
        ],
      },
      {
        order: 3,
        numberLabel: "03",
        icon: "chartbar",
        title: "Custom Internal Systems",
        description: "Tailored systems that streamline your operations and boost productivity.",
        features: [
          "Custom CRM Solutions",
          "Real-Time Analytics Dashboards",
          "Workflow Management Systems",
        ],
      },
      {
        order: 4,
        numberLabel: "04",
        icon: "zap",
        title: "Business Automation",
        description: "Automate repetitive tasks and focus on what really matters for your growth.",
        features: [
          "Marketing & Sales Automation",
          "No-Code Solutions (Make, Zapier, N8N)",
          "Custom Workflow Automation",
        ],
      },
      {
        order: 5,
        numberLabel: "05",
        icon: "messagesquare",
        title: "Implementation Consulting",
        description: "Expert guidance to successfully implement and adopt new technologies.",
        features: [
          "Digital Transformation Strategy",
          "Team Training & Onboarding",
          "Ongoing Technical Support",
        ],
      },
    ],
    practicalBlockTitle: "Why Choose Us",
    practicalBlockSubtitle: "What makes us different",
    practicalBullets: [
      "Solutions deployed in weeks, not months",
      "Dedicated technical team for each project",
      "24/7 monitoring and support",
    ],
    ctaButtonLabel: "Start Your Project",
    ctaButtonLink: "#lead-form",
    helperText: "Ready to transform your business with technology",
    nextStepLabel: "Ready to start?",
    nextStepText: "Schedule your free consultation today",
  },
  reviewsSection: {
    title: "What Our Clients Say",
    subtitle: "Real results from businesses we've helped transform with technology.",
    embedUrl: "",
  },
  blogSection: {
    title: "Tech Insights & Updates",
    subtitle: "Latest articles on AI, automation, and digital transformation",
    viewAllText: "View All Articles",
    readMoreText: "Read More",
  },
  aboutSection: {
    label: "About Us",
    heading: "Tech Solutions That Drive Results",
    description: "We are a technology solutions company specializing in AI, automation, and custom software development. We help businesses leverage cutting-edge technology to scale, optimize operations, and stay ahead of the competition.",
    defaultImageUrl: "",
    highlights: [
      {
        title: "Innovation",
        description: "Leveraging the latest in AI and automation technology.",
      },
      {
        title: "Expertise",
        description: "Years of experience building scalable solutions.",
      },
      {
        title: "Custom Solutions",
        description: "Every solution tailored to your unique needs.",
      },
    ],
  },
  areasServedSection: {
    label: "Where We Serve",
    heading: "Serving Businesses Worldwide",
    description: "We work with companies across the globe, delivering remote and on-site solutions.",
    ctaText: "Contact Us",
  },
  consultingStepsSection: {
    enabled: true,
    sectionId: "how-it-works",
    title: "How We Work",
    subtitle: "Our proven process for delivering successful tech solutions.",
    steps: [
      {
        order: 1,
        numberLabel: "01",
        icon: "search",
        title: "Discovery & Analysis",
        whatWeDo: "We dive deep into your business processes, challenges, and goals to understand exactly what you need.",
        outcome: "A clear roadmap of opportunities and technical solutions.",
      },
      {
        order: 2,
        numberLabel: "02",
        icon: "sparkles",
        title: "Solution Design",
        whatWeDo: "We architect the perfect tech stack and create a detailed implementation plan with timeline and ROI projections.",
        outcome: "A comprehensive proposal with transparent pricing and expected results.",
      },
      {
        order: 3,
        numberLabel: "03",
        icon: "layout",
        title: "Development & Testing",
        whatWeDo: "We build, test, and refine your solution using agile methodology with regular updates and previews.",
        outcome: "A fully functional, tested solution ready for deployment.",
      },
      {
        order: 4,
        numberLabel: "04",
        icon: "target",
        title: "Deployment & Support",
        whatWeDo: "We launch your solution, train your team, and provide ongoing monitoring and optimization.",
        outcome: "A live system with confident users and continuous improvement.",
      },
    ],
    practicalBlockTitle: "In Practice",
    practicalBullets: [
      "Agile sprints with weekly updates.",
      "Dedicated technical team.",
      "24/7 monitoring and support.",
    ],
    ctaButtonLabel: "Start Your Project",
    ctaButtonLink: "#lead-form",
    helperText: "Ready to transform your business with technology.",
    tagLabel: "Our Process",
    stepLabel: "Step",
    whatWeDoLabel: "What we do",
    outcomeLabel: "You get",
    practicalBlockSubtitle: "How the work happens day-to-day",
    nextStepLabel: "Next step",
    nextStepText: "Schedule open for new projects",
  },
};

export const DEFAULT_COMPANY_SETTINGS_SEED: Partial<InsertCompanySettings> = {
  companyName: "Skale Club",
  companyEmail: "contact@skaleclub.com",
  companyPhone: "",
  heroTitle: "Stop Doing Repetitive Work. Automate It.",
  heroSubtitle: "From AI chatbots to custom dashboards - we build the tech your business actually needs",
  ctaText: "See How We Can Help",
  seoTitle: "Skale Club - AI Automation & Custom Software Development",
  seoDescription: "We automate repetitive work with AI chatbots, smart websites, custom systems, and business automation. Built for companies ready to scale.",
  homepageContent: DEFAULT_TECH_HOMEPAGE_CONTENT,
};

export const DEFAULT_FAQS: InsertFaq[] = [
  {
    question: "Qual e a politica de cancelamento?",
    answer: "Voce pode cancelar ou reagendar seu servico gratuitamente ate 24 horas antes do horario agendado. Cancelamentos com menos de 24 horas de antecedencia estao sujeitos a uma taxa. Para cancelar, entre em contato conosco por telefone, email ou chat.",
    order: 1,
  },
  {
    question: "Quais sao as formas de pagamento?",
    answer: "Aceitamos diversas formas de pagamento para sua conveniencia: cartao de credito, debito, PIX e transferencia bancaria.",
    order: 2,
  },
  {
    question: "Voces oferecem garantia de satisfacao?",
    answer: "Sim! Garantimos 100% de satisfacao em todos os nossos servicos. Se voce nao ficar completamente satisfeito, faremos o possivel para corrigir a situacao. Sua satisfacao e nossa prioridade.",
    order: 3,
  },
  {
    question: "Como agendo um servico?",
    answer: "Voce pode agendar diretamente pelo nosso site, clicando em 'Agendar', ou entrando em contato atraves do nosso chat ou telefone.",
    order: 4,
  },
  {
    question: "Qual e o horario de atendimento?",
    answer: "Nosso horario de atendimento e de segunda a sexta, das 8h as 18h. Para horarios especiais ou finais de semana, consulte nossa disponibilidade.",
    order: 5,
  },
  {
    question: "Voces atendem em quais regioes?",
    answer: "Atendemos toda a regiao metropolitana. Para confirmar se atendemos seu endereco especifico, por favor entre em contato ou verifique no momento do agendamento.",
    order: 6,
  },
];

export const DEFAULT_PORTFOLIO_SERVICES: PortfolioServiceSeed[] = [
  {
    slug: "astropilot",
    title: "Astropilot",
    subtitle: "Social Media AI Creator",
    description: "Automate your social media presence with AI-powered content creation. Generate engaging posts, captions, and visuals that resonate with your audience.",
    price: "$497",
    priceLabel: "/month",
    badgeText: "AI Powered",
    features: ["AI Content Generation", "Multi-Platform Posting", "Hashtag Optimization", "Engagement Analytics", "Content Calendar"],
    iconName: "sparkles",
    ctaText: "Get Started",
    ctaButtonColor: "#8B5CF6",
    backgroundColor: "bg-gradient-to-br from-[#1a1a2e] to-[#2d1b4e]",
    accentColor: "purple",
    layout: "right",
    order: 1,
    isActive: true,
  },
  {
    slug: "websites",
    title: "Websites",
    subtitle: "Basic & Custom Solutions",
    description: "Professional websites tailored to your business needs. From simple landing pages to complex web applications, we build solutions that convert visitors into customers.",
    price: "$1,997",
    priceLabel: "starting",
    badgeText: "Popular",
    features: ["Responsive Design", "SEO Optimized", "Fast Loading", "Contact Forms", "Analytics Integration"],
    iconName: "globe",
    ctaText: "Start Project",
    ctaButtonColor: "#406EF1",
    backgroundColor: "bg-gradient-to-br from-[#0f2027] to-[#203a43]",
    accentColor: "blue",
    layout: "left",
    order: 2,
    isActive: true,
  },
  {
    slug: "chatbot",
    title: "Chatbot",
    subtitle: "SMS / WhatsApp / Telegram / Web",
    description: "Intelligent chatbots that engage customers across all major messaging platforms. Automate support, qualify leads, and book appointments 24/7.",
    price: "$797",
    priceLabel: "/month",
    badgeText: "Multi-Channel",
    features: ["SMS Integration", "WhatsApp Business", "Telegram Bot", "Website Widget", "Lead Qualification"],
    iconName: "message-circle",
    ctaText: "Learn More",
    ctaButtonColor: "#10B981",
    backgroundColor: "bg-gradient-to-br from-[#0d3b2e] to-[#0f2027]",
    accentColor: "green",
    layout: "right",
    order: 3,
    isActive: true,
  },
  {
    slug: "payment-system",
    title: "Payment System",
    subtitle: "Stripe Integration",
    description: "Seamless payment processing with Stripe integration. Accept payments online, set up subscriptions, and manage invoices with ease.",
    price: "$397",
    priceLabel: "one-time",
    badgeText: "Essential",
    features: ["Stripe Setup", "Payment Forms", "Subscription Management", "Invoice Generation", "Secure Transactions"],
    iconName: "credit-card",
    ctaText: "Get Started",
    ctaButtonColor: "#6366F1",
    backgroundColor: "bg-gradient-to-br from-[#1e1b4b] to-[#312e81]",
    accentColor: "blue",
    layout: "left",
    order: 4,
    isActive: true,
  },
  {
    slug: "voice-assistant",
    title: "Voice Assistant",
    subtitle: "AI Helping With Your Needs",
    description: "Deploy intelligent voice assistants that handle calls, answer questions, and provide customer support around the clock with natural conversation.",
    price: "$1,297",
    priceLabel: "/month",
    badgeText: "AI Powered",
    features: ["24/7 Availability", "Natural Voice", "Call Routing", "Appointment Booking", "Multi-Language"],
    iconName: "phone",
    ctaText: "Book Demo",
    ctaButtonColor: "#F59E0B",
    backgroundColor: "bg-gradient-to-br from-[#1a1a2e] to-[#16213e]",
    accentColor: "orange",
    layout: "right",
    order: 5,
    isActive: true,
  },
  {
    slug: "scheduling-system",
    title: "Scheduling System",
    subtitle: "Never Miss a Booking",
    description: "Automated scheduling that syncs with your calendar, sends reminders, and reduces no-shows. Perfect for service-based businesses.",
    price: "$297",
    priceLabel: "/month",
    badgeText: "Essential",
    features: ["Calendar Sync", "Automated Reminders", "Online Booking", "Timezone Support", "Team Scheduling"],
    iconName: "calendar",
    ctaText: "Get Started",
    ctaButtonColor: "#EC4899",
    backgroundColor: "bg-gradient-to-br from-[#831843] to-[#1a1a2e]",
    accentColor: "red",
    layout: "left",
    order: 6,
    isActive: true,
  },
  {
    slug: "crm-setup",
    title: "CRM Setup",
    subtitle: "Go High Level Integration",
    description: "Complete CRM setup with Go High Level. Manage leads, automate follow-ups, and track your sales pipeline in one powerful platform.",
    price: "$597",
    priceLabel: "one-time",
    badgeText: "Recommended",
    features: ["GHL Setup", "Pipeline Configuration", "Email Automation", "SMS Campaigns", "Reporting Dashboard"],
    iconName: "users",
    ctaText: "Get Started",
    ctaButtonColor: "#14B8A6",
    backgroundColor: "bg-gradient-to-br from-[#134e4a] to-[#0f2027]",
    accentColor: "green",
    layout: "right",
    order: 7,
    isActive: true,
  },
  {
    slug: "openclaw-deployment",
    title: "OpenClaw Deployment",
    subtitle: "Custom AI Deployment",
    description: "Deploy custom AI solutions tailored to your business needs. Automate complex workflows and integrate AI into your existing systems.",
    price: "$2,497",
    priceLabel: "starting",
    badgeText: "Premium",
    features: ["Custom AI Models", "Workflow Automation", "API Integration", "Training & Support", "Scalable Infrastructure"],
    iconName: "cpu",
    ctaText: "Contact Us",
    ctaButtonColor: "#EF4444",
    backgroundColor: "bg-gradient-to-br from-[#1a1a1a] to-[#2d2d2d]",
    accentColor: "red",
    layout: "left",
    order: 8,
    isActive: true,
  },
];
