// Seed the nfc-keychain-leads form + the NFC keychain landing / pricing pages.
// Idempotent: re-running updates all rows in place (same row ids preserved).
//
// Run: npx tsx --env-file=.env scripts/seed-nfc-keychains-landing.ts
//
// Creates / updates (5 rows):
//   1. forms   WHERE slug = 'nfc-keychain-leads'
//   2. pages   WHERE slug = 'nfc-keychains'    (landing,   EN, language='en')
//   3. pages   WHERE slug = 'nfc-keychains-br' (landing,   PT, language='pt')
//   4. pages   WHERE slug = 'nfc-pricing'      (explainer, EN) -> DEACTIVATED
//   5. pages   WHERE slug = 'nfc-pricing-br'   (explainer, PT) -> DEACTIVATED
//      Since 2026-09-22 the explainer lives inside the landing and its URLs
//      301 to /nfc-keychains (server/canonicalHost.ts). PRICING_SECTIONS below
//      is kept for reference only; nothing writes it any more.
//
// The PT slugs stay single-segment (the DB forbids a slash), but their public
// URLs are the two-segment /nfc-keychains/br and /nfc-pricing/br served by the
// /:slug/br client route (quick 260906-qwl). The legacy one-segment
// /nfc-keychains-br and /nfc-pricing-br URLs keep working too.
//
// The landing pair shares LANDING_SECTIONS [heroWebsites, trustBadges,
// featureGrid x2, processStepper, faqAccordion, leadFormCta], all dark. The explainer pair shares
// PRICING_SECTIONS [contentBlocks, pricingTable, processStepper, faqAccordion,
// leadFormCta]. Copy is t()-based so the pages.language column drives EN vs
// PT; each pair carries a reciprocal alternateSlug for hreflang.
//
// Pricing facts used in copy: the volume tiers, the 20-piece minimum, and the
// $50 one-time art fee are ALL read from shared/nfc-pricing.ts — the pricing
// table on this page is GENERATED by buildPriceLines() (shared/nfc-price-lines.ts),
// the same helper scripts/seed-nfc-order-page.ts and PricingTableSection.tsx's
// default lines use, so this page can never quote a price the order form does
// not charge. 100% payment upfront before production starts.
// No turnaround time is stated anywhere: the "how long does it take?" FAQ
// deliberately says the window is confirmed in writing at order approval.
//
// Both leadFormCta sections below (landing and pricing) open the PRICED order
// form (ORDER_FORM_SLUG = 'nfc-keychain-order', seeded by
// scripts/seed-nfc-order-form.ts) rather than the unpriced form this file
// seeds — see the note above ORDER_FORM_SLUG.
import "dotenv/config";
import { pathToFileURL } from "node:url";
import { eq } from "drizzle-orm";
import { pool, db } from "../server/db.js";
import { pages, type PageSection } from "../shared/schema/pages.js";
import { forms } from "../shared/schema/forms.js";
import type { FormConfig, FormQuestion } from "../shared/schema/forms.js";
import { buildPriceLines, nfcPriceCopy } from "../shared/nfc-price-lines.js";

// ── Config ────────────────────────────────────────────────────────────────

// Still seeded below so existing leads keep referencing it and /f/nfc-keychain-leads
// stays reachable, but NEITHER page's leadFormCta opens this form anymore —
// both point at ORDER_FORM_SLUG instead (see PRICING_SECTIONS / LANDING_SECTIONS).
const FORM_SLUG = "nfc-keychain-leads";
const FORM_NAME = "NFC Keychain Leads";
const FORM_DESCRIPTION =
  "Leads for the NFC keychain landing / pricing pages — business owners ordering custom 3D-printed NFC keychains.";

// The priced order form (scripts/seed-nfc-order-form.ts). Both the landing and
// the pricing page send their leadFormCta here now, so a lead never has to
// fill an unpriced form and then a priced one — one form, one submission.
const ORDER_FORM_SLUG = "nfc-keychain-order";

// ── Form questions (ENGLISH source copy) ──────────────────────────────────
//
// ID → storage mapping notes:
// - ALL copy here MUST be authored in English. English is the t() SOURCE
//   language: LeadFormModal renders t(question.title), which passes English
//   through untouched on the EN pages and auto-translates it on the PT ones.
//   Authoring Portuguese here would leak PT copy onto /nfc-keychains.
// - IDs `nome`, `email`, `telefone` map to native form_leads columns.
// - `tipoNegocio` ALSO maps to a native column (form_leads.tipo_negocio). It is
//   listed in shared/form.ts KNOWN_FIELD_IDS, so LeadFormModal.persistProgress
//   filters it OUT of customAnswers and sends it as a top-level payload field.
//   formLeadProgressSchema caps `tipoNegocio` at 120 chars — keep its option
//   `value` strings short kebab-case.
// - `observacoes` falls through to customAnswers even though a same-named
//   native column exists: it is NOT in KNOWN_FIELD_IDS and persistProgress
//   never sets it. Same behavior as the barbershop seed.
// - Every remaining ID (nomeEmpresa, quantidadeEstimada, objetivoChaveiro,
//   jaTemLogo, prazoDesejado, tipoVisita) falls through into
//   form_leads.customAnswers (jsonb).
// - `points` is 0 for every option — this form is NOT scored; all leads route
//   as `novo` regardless of answers.
// - Question 2 uses the `phoneCountry` type (Plan 44-03), which renders the
//   inline country selector + phone input as a single field, overrides
//   payload.telefone with the international number, and stashes
//   customAnswers.countryCode.

const NFC_KEYCHAIN_LEADS_QUESTIONS: FormQuestion[] = [
  {
    id: "nome",
    order: 1,
    title: "What's your name?",
    type: "text",
    required: true,
    placeholder: "Your full name",
  },
  {
    id: "telefone",
    order: 2,
    title: "What's your WhatsApp?",
    type: "phoneCountry", // ← inline country selector + phone input (44-03)
    required: true,
    placeholder: "(555) 123-4567",
  },
  {
    id: "email",
    order: 3,
    title: "What's your email?",
    type: "email",
    required: true,
    placeholder: "you@yourbusiness.com",
  },
  {
    id: "nomeEmpresa", // → customAnswers.nomeEmpresa
    order: 4,
    title: "What's the name of your business?",
    type: "text",
    required: true,
    placeholder: "Your business name",
  },
  {
    id: "tipoNegocio", // → native form_leads.tipo_negocio column (KNOWN_FIELD_IDS)
    order: 5,
    title: "What type of business do you have?",
    type: "select",
    required: true,
    options: [
      { value: "restaurant-food",        label: "Restaurant / food",          points: 0 },
      { value: "beauty-barbershop",      label: "Beauty salon / barbershop",  points: 0 },
      { value: "cleaning-home-services", label: "Cleaning / home services",   points: 0 },
      { value: "auto-services",          label: "Auto services",              points: 0 },
      { value: "retail-store",           label: "Retail / store",             points: 0 },
      { value: "health-fitness",         label: "Health / fitness",           points: 0 },
      { value: "other",                  label: "Other",                      points: 0 },
    ],
  },
  {
    id: "quantidadeEstimada", // → customAnswers.quantidadeEstimada
    order: 6,
    title: "How many keychains do you need?",
    type: "select",
    required: true,
    // Options are anchored on the 20-piece minimum order.
    options: [
      { value: "20",       label: "20 pieces (minimum order)", points: 0 },
      { value: "21-50",    label: "21-50 pieces",              points: 0 },
      { value: "51-100",   label: "51-100 pieces",             points: 0 },
      { value: "100-plus", label: "100+ pieces",               points: 0 },
      { value: "not-sure", label: "Not sure yet",              points: 0 },
    ],
  },
  {
    id: "objetivoChaveiro", // → customAnswers.objetivoChaveiro
    order: 7,
    title: "What should the tap open?",
    type: "select",
    required: true,
    options: [
      { value: "google-reviews", label: "Google review page",            points: 0 },
      { value: "instagram",      label: "Instagram",                     points: 0 },
      { value: "vcard",          label: "Digital business card (vCard)", points: 0 },
      { value: "menu",           label: "Menu",                          points: 0 },
      { value: "website",        label: "Website",                       points: 0 },
      { value: "multiple",       label: "More than one of these",        points: 0 },
    ],
  },
  {
    id: "jaTemLogo", // → customAnswers.jaTemLogo
    order: 8,
    title: "Do you have a logo?",
    type: "select",
    required: true,
    // Signals whether the $50 first-order art / design fee applies (and how
    // much design work is needed). The fee is NOT stated in the labels — the
    // pricing page explains it.
    options: [
      { value: "has-file",   label: "Yes, I have my logo in a file",   points: 0 },
      { value: "no-file",    label: "I have a logo but not the file",  points: 0 },
      { value: "needs-logo", label: "No, I need one created",          points: 0 },
    ],
  },
  {
    id: "prazoDesejado", // → customAnswers.prazoDesejado
    order: 9,
    title: "When do you want them?",
    type: "select",
    required: true,
    // Urgency only — no SLA is promised anywhere in this form or its pages.
    options: [
      { value: "asap",        label: "As soon as possible",      points: 0 },
      { value: "this-month",  label: "Within this month",        points: 0 },
      { value: "next-month",  label: "Next month",               points: 0 },
      { value: "researching", label: "Just researching for now", points: 0 },
    ],
  },
  // ── Xphere booking integration hook point ────────────────────────────────
  // tipoVisita captures the MEETING FORMAT only. Actual date/slot picking is a
  // deliberate follow-up: Xphere (the separate ops platform at
  // C:\Users\Vanildo\Dev\xphere) owns Calendly-style scheduling, and this
  // answer is the branch point where the free-slots picker will be injected
  // later. Do NOT add a date/time question here — no such form question type
  // exists.
  {
    id: "tipoVisita", // → customAnswers.tipoVisita
    order: 10,
    title: "How would you like to talk to us?",
    type: "select",
    required: true,
    options: [
      { value: "presencial", label: "In-person visit at my business", points: 0 },
      { value: "online",     label: "Online meeting (video call)",    points: 0 },
      { value: "whatsapp",   label: "WhatsApp only",                  points: 0 },
    ],
  },
  {
    id: "observacoes", // → customAnswers.observacoes (NOT the native column — see notes above)
    order: 11,
    title: "Anything else we should know?",
    type: "text",
    required: false,
    placeholder: "Optional",
  },
];

const NFC_KEYCHAIN_LEADS_CONFIG: FormConfig = {
  questions: NFC_KEYCHAIN_LEADS_QUESTIONS,
  maxScore: 0,
  thresholds: { hot: 0, warm: 0, cold: 0 }, // not scored — all leads land as `novo`
};

// ── Landing sections (in render order) ─────────────────────────────────────

// Shared processStepper props for this product. Used by BOTH the landing and
// the pricing page so the two never drift apart. `icons` must be names from
// the processStepperIconNames allowlist in ProcessStepperSection.tsx.
// Step descriptions contain NO day/week counts — turnaround is never claimed.
const NFC_STEPPER_PROPS = {
  eyebrow:    "How it works",
  heading:    "From first message to tapping in 4 steps",
  subheading: "A simple process with no surprises. You approve every step before we move on.",
  steps: [
    {
      title:       "Talk to us",
      description: "Tell us what the tap should open and how many keychains you need. We confirm the details with you on WhatsApp.",
    },
    {
      title:       "We design your art",
      description: "Send us your logo file, or we create the artwork for you. You approve the design before anything is produced.",
    },
    {
      title:       "We print and program",
      description: "Each keychain is 3D-printed with your design, and the NFC tag inside is programmed with your link and tested.",
    },
    {
      title:       "You receive and start tapping",
      description: "Your keychains arrive ready to use. Hand them out, put one on the counter, and watch the taps come in.",
    },
  ],
  icons: ["MessageCircle", "PenTool", "Factory", "Truck"],
};

// Sections are IDENTICAL for both languages — the pages.language column drives
// EN vs PT through t(). The hero and CTA carry explicit English copy props
// (NFC-keychain-specific messaging). No pricing in the hero: the ad landing
// captures the lead; the pricing page (sent by WhatsApp automation) closes.
// No bgVideoUrl: the /websites video asset is specific to that page.
// Landing redesign (2026-09-22): one selling page. No price table anywhere on
// it: the order form shows the exact price as a preview and the final total is
// confirmed on WhatsApp. The only number is the entry price in the FAQ and
// under the closing button, read from shared/nfc-pricing.ts via nfcPriceCopy().
// The Google reviews section is gone: every review is about websites.
const PRICE_COPY = nfcPriceCopy();

export const LANDING_SECTIONS: PageSection[] = [
  {
    type: "heroWebsites",
    props: {
      theme: "dark",
      eyebrow: "Custom NFC keychains",
      headline: "One tap. Your customers land exactly where you want them.",
      subheadline: "Custom 3D-printed NFC keychains with your logo. A customer taps their phone and opens your Google review page, Instagram, digital business card, menu, or website. No app needed.",
      ctaLabel: "I want my keychains",
      secondaryCtaLabel: "See how it works",
      secondaryCtaHref: "#how-it-works",
      backgroundImageUrl: "/nfc-keychains-hero.webp",
      backgroundImageAlt: "Custom 3D-printed NFC keychains in different designs",
    },
  },
  {
    type: "trustBadges",
    props: {
      theme: "dark",
      badges: [
        { title: "Programmed and tested", description: "Every NFC tag is checked before shipping", icon: "badgecheck" },
        { title: "Custom 3D design", description: "Made with your logo and approved artwork", icon: "sparkles" },
        { title: "No app required", description: "Works with modern iPhone and Android phones", icon: "zap" },
      ],
    },
  },
  {
    type: "featureGrid",
    props: {
      theme: "dark",
      eyebrow: "What the tap opens",
      heading: "You choose where every tap goes",
      subheading: "One link per keychain. Point it at a page you control and you can change it anytime.",
      items: [
        { icon: "Star", title: "Google reviews", description: "Customers leave a review right at the counter, while the visit is still fresh." },
        { icon: "Instagram", title: "Instagram", description: "New followers in one tap, no searching for your profile." },
        { icon: "IdCard", title: "Digital business card", description: "Your contact saved straight to their phone." },
        { icon: "UtensilsCrossed", title: "Menu", description: "Always up to date, with no reprinting." },
        { icon: "MessageCircle", title: "WhatsApp", description: "A chat with your business opens in one tap." },
        { icon: "Globe", title: "Website or booking page", description: "Send people straight to where they book or buy." },
      ],
    },
  },
  {
    type: "featureGrid",
    props: {
      theme: "dark",
      eyebrow: "Where to use it",
      heading: "Wherever your customers are within reach",
      subheading: "Put one at every point of contact.",
      items: [
        { icon: "Store", title: "At the counter", description: "Next to the register, where every customer passes." },
        { icon: "ConciergeBell", title: "At reception", description: "On the front desk or in the waiting area." },
        { icon: "Car", title: "In your vehicle", description: "In the car or truck, if you offer mobile services." },
        { icon: "KeyRound", title: "On your keyring", description: "Always one on hand to give away." },
      ],
    },
  },
  { type: "processStepper", props: { ...NFC_STEPPER_PROPS, theme: "dark", anchorId: "how-it-works" } },
  {
    type: "faqAccordion",
    props: {
      theme:      "dark",
      eyebrow:    "FAQ",
      heading:    "Questions people ask before ordering",
      subheading: "Everything you need to decide, without waiting for a reply.",
      items: [
        {
          question: "What exactly is an NFC keychain?",
          answer:   "A 3D-printed keychain with your logo and a small NFC tag inside. When a customer taps their phone on it, the phone opens the link you chose: your Google review page, Instagram, digital business card, menu, or website.",
        },
        {
          question: "Do my customers need to install an app?",
          answer:   "No. Modern iPhones and Android phones read NFC tags natively, the same way they handle tap-to-pay. The customer just holds the phone close to the keychain and a notification opens the link.",
        },
        {
          question: "Can you make a keychain in the shape of an object?",
          answer:   "Yes. Besides the flat keychain with your logo, we make them with raised relief and in custom shapes, like your product, a tool from your trade or your logo cut out. You pick the style in the order form, and we confirm the details with you on WhatsApp.",
        },
        { question: "How much does it cost?", answer: PRICE_COPY.faqAnswer.en },
        {
          question: "Can I change the link later?",
          answer:   "Yes. We recommend pointing the tag to a link you control, like a short link or a page on your website, so you can redirect it whenever you want without touching the keychain. If you need the tag itself reprogrammed, message us and we will walk you through the options.",
        },
        {
          question: "Why is payment 100% upfront?",
          answer:   "Every order is custom-made with your logo, so it cannot be resold or reused for another business. Paying in full before production covers the materials and the work, and it lets us start right away. You still approve the design before anything is printed.",
        },
        {
          // Deliberate omission: NO number here (see the file header).
          question: "How long does it take?",
          answer:   "Production starts as soon as your payment clears and the artwork is approved. The exact production and delivery window is confirmed in writing when your order is approved, so you know what to expect before you commit.",
        },
        {
          question: "What if I do not have a logo?",
          answer:   "Upload the best version you have. A clear photo or a screenshot usually works, and we prepare it for 3D printing. If you have no logo at all, we create the artwork for you.",
        },
      ],
    },
  },
  {
    type: "leadFormCta",
    props: {
      theme: "dark",
      formSlug: ORDER_FORM_SLUG,
      heading: "Ready to get your keychains?",
      subheading:
        "About a minute to fill in. You see the price as you choose the quantity, and we confirm everything with you on WhatsApp before producing anything. Sending the form costs nothing.",
      ctaLabel: "I want my keychains",
      note: PRICE_COPY.ctaNote.en,
      imageUrl: "/nfc-keychains-hero.webp",
      imageAlt: "Custom 3D-printed NFC keychains in different designs",
    },
  },
];

// ── Pricing / explainer sections (in render order) ─────────────────────────

// This page is sent to a lead by WhatsApp automation and must close price,
// process, timeline, and objections with no human present. Every number here
// is from the confirmed pricing block at the top of this file.
const PRICING_SECTIONS: PageSection[] = [
  {
    type: "contentBlocks",
    props: {
      theme:      "dark",
      eyebrow:    "How it works",
      heading:    "NFC keychains, explained",
      headingLevel: "h1",
      subheading: "What they are, where they work, and what you need to get started.",
      blocks: [
        {
          heading: "What is an NFC keychain?",
          paragraphs: [
            "An NFC keychain is a small 3D-printed keychain with your logo on the outside and a tiny NFC tag inside. When a customer touches the back of their phone to it, the phone opens a link you choose. No app to download, nothing to type.",
            "Modern iPhones and Android phones read NFC tags natively — it is the same technology behind tap-to-pay. You pick what the tap opens:",
          ],
          bullets: [
            "Google review page — collect more reviews right at the counter",
            "Instagram — new followers in one tap",
            "Digital business card (vCard) — your contact saved straight to their phone",
            "Menu — no more printed menus going out of date",
            "Website — send people directly to your booking or store page",
          ],
        },
        {
          heading: "Where businesses use it",
          paragraphs: [
            "The keychain works anywhere your customers are within arm's reach of it. Put one at every point of contact:",
          ],
          bullets: [
            "On the counter next to the register",
            "At the reception desk or in the waiting area",
            "Inside your car or truck if you offer mobile services",
            "On your own keyring, so you always have one to hand out",
            "On a table tent in a restaurant, salon, or barbershop",
          ],
        },
        {
          heading: "What you get and what we need from you",
          paragraphs: [
            "Every order includes the 3D-printed keychains with your design, the NFC tag inside each one programmed with your link, and a test of every piece before it ships.",
            "To get started, we need your logo as a file (PNG, JPG, WEBP or PDF) and the link you want the tap to open. If you do not have a logo file, we create the artwork for you — that is what the first-order art fee covers.",
          ],
        },
      ],
    },
  },
  {
    type: "pricingTable",
    props: {
      theme:      "dark",
      eyebrow:    "Pricing",
      heading:    "Simple, upfront pricing",
      subheading: "No hidden fees. You know the total before we start.",
      lines: buildPriceLines(),
      footnote: "100% payment upfront. Production starts after payment clears.",
    },
  },
  { type: "processStepper", props: { ...NFC_STEPPER_PROPS, theme: "dark" } }, // same steps + icons as the landing
  {
    type: "faqAccordion",
    props: {
      theme:      "dark",
      eyebrow:    "FAQ",
      heading:    "Questions people ask before ordering",
      subheading: "Everything you need to decide, without waiting for a reply.",
      items: [
        {
          question: "What exactly is an NFC keychain?",
          answer:   "A 3D-printed keychain with your logo and a small NFC tag inside. When a customer taps their phone on it, the phone opens the link you chose: your Google review page, Instagram, digital business card, menu, or website.",
        },
        {
          question: "Do my customers need to install an app?",
          answer:   "No. Modern iPhones and Android phones read NFC tags natively, the same way they handle tap-to-pay. The customer just holds the phone close to the keychain and a notification opens the link.",
        },
        {
          question: "Why is there a minimum order?",
          answer:   "Each order is set up, designed, printed, and programmed as a batch, so very small runs do not make sense for either side. The minimum is 20 pieces, which comes to $200 at the 20-piece price — and the price per piece drops as you order more. Twenty pieces is enough to put one at every point of contact and hand some out to your team.",
        },
        {
          question: "What is the $50 art fee, and when is it waived?",
          answer:   "The $50 art / design fee covers preparing your logo for 3D printing and creating the artwork if you do not have a file yet. It is charged once, on your first order only. From your second order onward it is waived, because the artwork is already done.",
        },
        {
          question: "Can I change the link later?",
          answer:   "Yes. We recommend pointing the tag to a link you control, like a short link or a page on your website, so you can redirect it whenever you want without touching the keychain. If you need the tag itself reprogrammed, message us and we will walk you through the options.",
        },
        {
          question: "Why is payment 100% upfront?",
          answer:   "Every order is custom-made with your logo, so it cannot be resold or reused for another business. Paying in full before production covers the materials and the work, and it lets us start right away. You still approve the design before anything is printed.",
        },
        {
          // Deliberate omission: NO number here. If a published SLA is wanted
          // later, edit this answer in the admin page editor — no code change.
          question: "How long does it take?",
          answer:   "Production starts as soon as your payment clears and the artwork is approved. The exact production and delivery window is confirmed in writing when your order is approved, so you know what to expect before you commit.",
        },
        {
          question: "What if I do not have a logo?",
          answer:
            "No logo file? Upload the best version you have — a clear photo or a screenshot usually works, and the first-order art fee covers preparing it for 3D printing. If you have no logo at all, we create the artwork for you.",
        },
      ],
    },
  },
  {
    type: "leadFormCta",
    props: {
      theme: "dark",
      formSlug: ORDER_FORM_SLUG,
      heading: "Ready to order?",
      subheading:
        "About a minute to fill in. It shows the price as you choose the quantity, you send your logo, and we confirm everything with you on WhatsApp before producing anything. Sending the form does not charge you anything.",
      ctaLabel: "I want to order",
    },
  },
];

// ── Page specs ─────────────────────────────────────────────────────────────

type LandingSpec = {
  slug: string;
  name: string;
  language: "en" | "pt";
  alternateSlug: string;
  sections: PageSection[];
};

// Two bilingual pairs. Same sections within each pair; only the language +
// alternateSlug differ (reciprocal alternateSlug drives hreflang).
const LANDING_EN: LandingSpec = { slug: "nfc-keychains",    name: "NFC Keychains (EN)", language: "en", alternateSlug: "nfc-keychains-br", sections: LANDING_SECTIONS };
const LANDING_PT: LandingSpec = { slug: "nfc-keychains-br", name: "NFC Keychains (PT)", language: "pt", alternateSlug: "nfc-keychains",    sections: LANDING_SECTIONS };
const PRICING_EN: LandingSpec = { slug: "nfc-pricing",      name: "NFC Pricing (EN)",   language: "en", alternateSlug: "nfc-pricing-br",   sections: PRICING_SECTIONS };
const PRICING_PT: LandingSpec = { slug: "nfc-pricing-br",   name: "NFC Pricing (PT)",   language: "pt", alternateSlug: "nfc-pricing",      sections: PRICING_SECTIONS };

// ── Seed runner ───────────────────────────────────────────────────────────

async function upsertForm() {
  console.log(`Seeding form: slug='${FORM_SLUG}'`);
  const existing = await db.select().from(forms).where(eq(forms.slug, FORM_SLUG));

  if (existing.length > 0) {
    const [row] = await db
      .update(forms)
      .set({
        name:        FORM_NAME,
        description: FORM_DESCRIPTION,
        config:      NFC_KEYCHAIN_LEADS_CONFIG,
        isActive:    true,
        isDefault:   false,
        updatedAt:   new Date(),
      })
      .where(eq(forms.slug, FORM_SLUG))
      .returning();
    console.log(`  Updated existing form (id=${row.id}).`);
    return row;
  } else {
    const [row] = await db
      .insert(forms)
      .values({
        slug:        FORM_SLUG,
        name:        FORM_NAME,
        description: FORM_DESCRIPTION,
        config:      NFC_KEYCHAIN_LEADS_CONFIG,
        isActive:    true,
        isDefault:   false,
      })
      .returning();
    console.log(`  Inserted new form (id=${row.id}).`);
    return row;
  }
}

async function upsertLanding(spec: LandingSpec) {
  console.log(`Seeding landing: slug='${spec.slug}' (${spec.language})`);
  const existing = await db
    .select()
    .from(pages)
    .where(eq(pages.slug, spec.slug));

  if (existing.length > 0) {
    const [row] = await db
      .update(pages)
      .set({
        name:          spec.name,
        sections:      spec.sections,
        isActive:      true,
        language:      spec.language,
        alternateSlug: spec.alternateSlug,
        updatedAt:     new Date(),
      })
      .where(eq(pages.slug, spec.slug))
      .returning();
    console.log(`  Updated existing landing (id=${row.id}).`);
    return row;
  } else {
    const [row] = await db
      .insert(pages)
      .values({
        slug:          spec.slug,
        name:          spec.name,
        sections:      spec.sections,
        isActive:      true,
        language:      spec.language,
        alternateSlug: spec.alternateSlug,
      })
      .returning();
    console.log(`  Inserted new landing (id=${row.id}).`);
    return row;
  }
}

async function deactivatePricingPages() {
  for (const spec of [PRICING_EN, PRICING_PT]) {
    const rows = await db
      .update(pages)
      .set({ isActive: false, updatedAt: new Date() })
      .where(eq(pages.slug, spec.slug))
      .returning({ id: pages.id });
    console.log(`  Pricing page '${spec.slug}': ${rows.length ? "deactivated" : "not found"}.`);
  }
}

// One-time cleanup for the 260906-qwl slug rename (chaveiros-nfc -> nfc-keychains-br,
// precos-chaveiros -> nfc-pricing-br). upsertLanding() keys on `slug`, so the renamed
// specs INSERT new rows and orphan the originals. Delete exactly these two slugs and
// nothing else. Idempotent: once they are gone this deletes zero rows and logs a no-op.
const RENAMED_LEGACY_SLUGS = ["chaveiros-nfc", "precos-chaveiros"] as const;

async function deleteRenamedLegacyPages() {
  for (const slug of RENAMED_LEGACY_SLUGS) {
    const deleted = await db
      .delete(pages)
      .where(eq(pages.slug, slug))
      .returning({ id: pages.id, slug: pages.slug });
    if (deleted.length > 0) {
      console.log(`  Deleted orphaned legacy page slug='${slug}' (id=${deleted[0].id}).`);
    } else {
      console.log(`  No page with slug='${slug}' — nothing to delete.`);
    }
  }
}

async function main() {
  await upsertForm();
  // Both leadFormCta sections point at ORDER_FORM_SLUG (a form this script does
  // NOT seed), so fail loudly here instead of letting the pages go live with a
  // dangling formSlug — LeadFormModal would silently fall back to the default
  // form and leads would 404 against the wrong form.
  const [orderForm] = await db.select({ id: forms.id }).from(forms).where(eq(forms.slug, ORDER_FORM_SLUG));
  if (!orderForm) throw new Error(`Form '${ORDER_FORM_SLUG}' is missing. Run scripts/seed-nfc-order-form.ts first.`);
  await upsertLanding(LANDING_EN);
  await upsertLanding(LANDING_PT);
  // The pricing explainer was folded into the landing (2026-09-22). Its rows
  // are switched off, not deleted; server/canonicalHost.ts 301s the URLs.
  await deactivatePricingPages();
  console.log("Cleaning up slugs renamed by quick 260906-qwl:");
  await deleteRenamedLegacyPages();
  console.log("Done.");
  await pool.end();
}

// Only seed when run directly: importing LANDING_SECTIONS (a preview script,
// a schema check) must not open a connection or write anything.
const runDirectly = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;

if (runDirectly) {
  main().catch(async (err) => {
    console.error("Seed failed:", err);
    try {
      await pool.end();
    } catch {
      /* noop */
    }
    process.exit(1);
  });
}
